In [1]:
import pandas as pd

# Define the data
data = {
    'customer_id': [1, 1, 2, 2, 3],
    'order_amount': [100, 200, 150, 50, 300],
    'order_date': ['2024-01-01', '2024-01-05', '2024-01-03', '2024-01-10', '2024-01-02']
}

# Create the DataFrame
df = pd.DataFrame(data)

# Convert 'order_date' to actual datetime objects
df['order_date'] = pd.to_datetime(df['order_date'])

print(df)

   customer_id  order_amount order_date
0            1           100 2024-01-01
1            1           200 2024-01-05
2            2           150 2024-01-03
3            2            50 2024-01-10
4            3           300 2024-01-02

Task 1 (Basic Filtering + Aggregation):

1. Find total order amount per customer

2. Return only customers with total > 200

In [4]:
df['total_order_amount'] = df.groupby('customer_id')['order_amount'].transform('sum')
df

   customer_id  order_amount order_date  total_order_amount
0            1           100 2024-01-01                 300
1            1           200 2024-01-05                 300
2            2           150 2024-01-03                 200
3            2            50 2024-01-10                 200
4            3           300 2024-01-02                 300

In [5]:
df.loc[df['total_order_amount'] > 200]

   customer_id  order_amount order_date  total_order_amount
0            1           100 2024-01-01                 300
1            1           200 2024-01-05                 300
4            3           300 2024-01-02                 300

Corrected code suggested in review.

- Transform returns row level output of the initial dataframe. It is not needed for the answer
- Think about how the stakeholders could easily read the output

In [21]:
result = (
    df.groupby('customer_id', as_index=False)['order_amount']
      .sum()
      .rename(columns={'order_amount': 'total_order_amount'})
)

result = result[result['total_order_amount'] > 200]
result

   customer_id  total_order_amount
0            1                 300
2            3                 300

Task 2 (Groupby + Ranking):

1. For each customer, find their largest order

2. Then return the top 2 customers based on that largest order

In [6]:
df.groupby('customer_id')['order_amount'].max()

customer_id
1    200
2    150
3    300
Name: order_amount, dtype: int64

In [10]:
df.groupby('customer_id')['order_amount'].max().sort_values(ascending = False).head(2)

customer_id
3    300
1    200
Name: order_amount, dtype: int64

In [17]:
df.groupby('customer_id', as_index=False)['order_amount'].max().rename(columns={'order_amount': 'largest_order'})

   customer_id  largest_order
0            1            200
1            2            150
2            3            300

Cleaner answer suggested in review.
- Returns a dataframe, 
- renamed columns, 
- production friendly

In [19]:
result = (
    df.groupby('customer_id', as_index=False)['order_amount']
      .max()
      .rename(columns={'order_amount': 'largest_order'})
      .sort_values(by='largest_order', ascending=False)
      .head(2)
)
result

   customer_id  largest_order
2            3            300
0            1            200